org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false


parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1

minecraft_version_range=[1.21.1, 1.22)

neo_version=21.1.62
neo_version_range=[21.1.0,)

bio_version=3.0.0
bio_version_range=[3.0,)

fd_version=1.2.6
fd_version_range=[1.2.6,)

nml_version=0.0.5-alpha
nml_version_range=[0.0.5-alpha,)

loader_version_range=[4,)

mod_id=newworld
mod_name=New World
mod_license=MIT
mod_version=1.21-1.5.4
mod_group_id=com.kryptography.newworld
mod_authors=AvocadoSpud, Krypto, DigitalPear
mod_description=A small mod that adds a biome to the world.